#Read the fish dataset in R
fish <- read.table("final_alignment.phylip")
library(tidyverse)
#Rename columns
colnames(fish) <- c("species_name","seq")
#Extract CO1 nucleotides
fishCO1 <- substr(fish$seq,2292,2973)
#Check the class of fishCO1 dataset
class(fishCO1)
#Convert to dataframe
fishCO1 <- data.frame(fishCO1)
#Check the converted dataset
class(fishCO1)
#Bind the column "species name" to the fishCO1 dataframe
fishCO1_with_speciesname <- cbind(fish$species_name,fishCO1)
#Replace "-" with nothing 
df_0 <- gsub('-','',fishCO1_with_speciesname$fishCO1)
#Convert to dataframe
df_0 <- as.data.frame(df_0)
#Bind the colum "species name" of fish dataset with new dataframe
df_1 <- cbind(fish$species_name,df_0)
#Remove rows with empty sequences
df_2 <- subset(df_1, df_1$df_0 != "")
fishsamplefull_co1_with_speciesname <- df_2
#Convert to phylip format to be used in EPA
dat2phylip(fishCO1_with_speciesname,outfile= "fishsamplefull_co1_with_speciesname.phy")
#Rename column names
colnames(df_2) <- c("species_name","seq")
#Keep only rows with sequences
fish_multigene <- merge(fish,df_2, by= "species_name")
#New dataframe with first two columns
fish_multigene <- fish_multigene[, 1:2]
#Rename columns
colnames(fish_multigene) <- c("species_name","seq")

#Extract the range of COI gene to be used in EPA
fishsamplefull_co1 <- substr(fish_multigene$seq,2292,2973)
#Check the class
class(fishsamplefull_co1)
#Convert to dataframe
fishsamplefull_co1 <- data.frame(fishsamplefull_co1)
#Check the class
class(fishsamplefull_co1)
#Combine columns of COI dataframe and fishsample100 dataframe to get the sepecies name
fishsamplefull_co1_with_speciesname <- cbind(fish_multigene$species_name,fishsamplefull_co1)
#Assign column names
colnames(fishsamplefull_co1_with_speciesname) <- c("species_name","seq")
#Convert to phylip format
dat2phylip(fishsamplefull_co1_with_speciesname,outfile= "fishsamplefull_co1_with_speciesname.phy")

library(ape)
library(phylotools)
#convert datafame to phylip format to use in RAxML
dat2phylip(fish_multigene,outfile= "fish_multigene.phy")
6796*(80/100)
6796-5437
6796*(60/100)
6796-4078
6796*(40/100)
6796-2718
6796*(20/100)
6796-1359

fishsamples <- function (fishsample_n,y){
  #fishsample_y <- fishsample100[sample(nrow(fishsample100), y),]
  #generate 10 replicatesout without replacement
  fishsample_y <- as.data.frame(replicate(10, fishsample_n[sample(nrow(fishsample_n),y, replace=F),])) 
  return(fishsample_y)
}
set.seed(13)
#Use the function "fishsamples" to generate 80% dataset
fishsample80F <- fishsamples(fish_multigene,5437)
#Separate dataframes in columns of mass fishsample80 dataframe
replicate_dataframesF <- c(fishsample80F$V1,fishsample80F$V2,fishsample80F$V3,fishsample80F$V4,fishsample80F$V5,fishsample80F$V6,fishsample80F$V7,fishsample80F$V8,fishsample80F$V9,fishsample80F$V10)
#function to generate dataframes from replicates
df <- function(rep_df){
  t8 <- as.data.frame(rep_df)
  return(t8)
}
# Use the function to generate replicate dataframes 
t9 <- df(replicate_dataframesF)
#Separte mass dataframe into a list
lst1 <- lapply(seq(1, ncol(t9), by=2), function(i) 
  t9[i: pmin((i+1), ncol(t9))])
#to get individual dataframes for each replicate
list2env(setNames(lst1, paste0("newdfF", seq_along(lst1))),
         envir=.GlobalEnv)
#Function to generate different level samples without replicates and replaces
fishsamples_no_rep <- function (fishsample_m,z){
  fishsample_z <- as.data.frame(fishsample_m[sample(nrow(fishsample_m), z),])
  #fishsample_y <- as.data.frame(replicate(10, fishsample_n[sample(nrow(fishsample_n),y, replace=F),])) 
  return(fishsample_z)
}
#Use the function to genetare phylip files from the dataframe
dff <- function(xx){
  
  return(dat2phylip(xx,outfile = "newphy.phy"))
  
}
#80% 1st dataframe convert to phylip
#dff(newdfF1)
dat2phylip(newdfF1,outfile= "fishsample80_1.phy")
fishsample60_1 <- fishsamples_no_rep(newdfF1,4078)
dat2phylip(fishsample60_1,outfile= "fishsample60_1.phy")
#dff(fishsample60_1)
fishsample40_1 <- fishsamples_no_rep(fishsample60_1,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_1,outfile= "fishsample40_1.phy")
fishsample20_1 <- fishsamples_no_rep(fishsample40_1,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_1,outfile= "fishsample20_1.phy")

#80% 2nd df
dat2phylip(newdfF2,outfile= "fishsample80_2.phy")
fishsample60_2 <- fishsamples_no_rep(newdfF2,4078)
dat2phylip(fishsample60_2,outfile= "fishsample60_2.phy")
#dff(fishsample60_1)
fishsample40_2 <- fishsamples_no_rep(fishsample60_2,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_2,outfile= "fishsample40_2.phy")
fishsample20_2 <- fishsamples_no_rep(fishsample40_2,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_2,outfile= "fishsample20_2.phy")

dat2phylip(newdfF3,outfile= "fishsample80_3.phy")
fishsample60_3 <- fishsamples_no_rep(newdfF3,4078)
dat2phylip(fishsample60_3,outfile= "fishsample60_3.phy")
#dff(fishsample60_1)
fishsample40_3 <- fishsamples_no_rep(fishsample60_3,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_3,outfile= "fishsample40_3.phy")
fishsample20_3 <- fishsamples_no_rep(fishsample40_3,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_3,outfile= "fishsample20_3.phy")

dat2phylip(newdfF4,outfile= "fishsample80_4.phy")
fishsample60_4 <- fishsamples_no_rep(newdfF4,4078)
dat2phylip(fishsample60_4,outfile= "fishsample60_4.phy")
#dff(fishsample60_1)
fishsample40_4 <- fishsamples_no_rep(fishsample60_4,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_4,outfile= "fishsample40_4.phy")
fishsample20_4 <- fishsamples_no_rep(fishsample40_4,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_4,outfile= "fishsample20_4.phy")

dat2phylip(newdfF5,outfile= "fishsample80_5.phy")
fishsample60_5 <- fishsamples_no_rep(newdfF5,4078)
dat2phylip(fishsample60_5,outfile= "fishsample60_5.phy")
#dff(fishsample60_1)
fishsample40_5 <- fishsamples_no_rep(fishsample60_5,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_5,outfile= "fishsample40_5.phy")
fishsample20_5 <- fishsamples_no_rep(fishsample40_5,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_5,outfile= "fishsample20_5.phy")

dat2phylip(newdfF6,outfile= "fishsample80_6.phy")
fishsample60_6 <- fishsamples_no_rep(newdfF6,4078)
dat2phylip(fishsample60_6,outfile= "fishsample60_6.phy")
#dff(fishsample60_1)
fishsample40_6 <- fishsamples_no_rep(fishsample60_6,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_6,outfile= "fishsample40_6.phy")
fishsample20_6 <- fishsamples_no_rep(fishsample40_6,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_6,outfile= "fishsample20_6.phy")

dat2phylip(newdfF7,outfile= "fishsample80_7.phy")
fishsample60_7 <- fishsamples_no_rep(newdfF7,4078)
dat2phylip(fishsample60_7,outfile= "fishsample60_7.phy")
#dff(fishsample60_1)
fishsample40_7 <- fishsamples_no_rep(fishsample60_7,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_7,outfile= "fishsample40_7.phy")
fishsample20_7 <- fishsamples_no_rep(fishsample40_7,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_7,outfile= "fishsample20_7.phy")

dat2phylip(newdfF8,outfile= "fishsample80_8.phy")
fishsample60_8 <- fishsamples_no_rep(newdfF8,4078)
dat2phylip(fishsample60_8,outfile= "fishsample60_8.phy")
#dff(fishsample60_1)
fishsample40_8 <- fishsamples_no_rep(fishsample60_8,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_8,outfile= "fishsample40_8.phy")
fishsample20_8 <- fishsamples_no_rep(fishsample40_8,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_8,outfile= "fishsample20_8.phy")

dat2phylip(newdfF9,outfile= "fishsample80_9.phy")
fishsample60_9 <- fishsamples_no_rep(newdfF9,4078)
dat2phylip(fishsample60_9,outfile= "fishsample60_9.phy")
#dff(fishsample60_1)
fishsample40_9 <- fishsamples_no_rep(fishsample60_9,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_9,outfile= "fishsample40_9.phy")
fishsample20_9 <- fishsamples_no_rep(fishsample40_9,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_9,outfile= "fishsample20_9.phy")

dat2phylip(newdfF10,outfile= "fishsample80_10.phy")
fishsample60_10 <- fishsamples_no_rep(newdfF10,4078)
dat2phylip(fishsample60_10,outfile= "fishsample60_10.phy")
#dff(fishsample60_1)
fishsample40_10 <- fishsamples_no_rep(fishsample60_10,2718)
#dff(fishsample40_1)
dat2phylip(fishsample40_10,outfile= "fishsample40_10.phy")
fishsample20_10 <- fishsamples_no_rep(fishsample40_10,1359)
#dff(fishsample20_1)
dat2phylip(fishsample20_10,outfile= "fishsample20_10.phy")

library(phangorn)
#Read trees into R generated from RAxML
aF <- read.tree("RAxML_parsimonyTree.multigeneTree")
bF <- read.tree("F20_1_NEW")   
cF <- read.tree("F20_2_NEW") 
dF <- read.tree("F20_3_NEW") 
eF <- read.tree("F20_4_NEW") 
fF <- read.tree("F20_5_NEW") 
gF <- read.tree("F20_6_NEW")   
hF <- read.tree("F20_7_NEW")     
iF <- read.tree("F20_8_NEW") 
jF <- read.tree("F20_9_NEW") 
kF <- read.tree("F20_10_NEW") 
lF <- read.tree("F40_1_NEW") 
mF <- read.tree("F40_2_NEW") 
nF <- read.tree("F40_3_NEW") 
oF <- read.tree("F40_4_NEW") 
pF <- read.tree("F40_5_NEW") 
qF <- read.tree("F40_6_NEW") 
rF <- read.tree("F40_7_NEW") 
sF <- read.tree("F40_8_NEW") 
tF <- read.tree("F40_9_NEW") 
uF <- read.tree("F40_10_NEW") 
vF <- read.tree("F60_1_NEW") 
wF <- read.tree("F60_2_NEW") 
xF <- read.tree("F60_3_NEW") 
yF <- read.tree("F60_4_NEW") 
zF <- read.tree("F60_5_NEW") 
aaF <- read.tree("F60_6_NEW") 
bbF <- read.tree("F60_7_NEW") 
ccF <- read.tree("F60_8_NEW")
ddF <- read.tree("F60_9_NEW")
eeF <- read.tree("F60_10_NEW")
ffF <- read.tree("F80_1_NEW")
ggF <- read.tree("F80_2_NEW")
hhF <- read.tree("F80_3_NEW")
iiF <- read.tree("F80_4_NEW")
jjF <- read.tree("F80_5_NEW")
kkF <- read.tree("F80_6_NEW")
llF <- read.tree("F80_7_NEW")
mmF <- read.tree("F80_8_NEW")
nnF <- read.tree("F80_9_NEW")
ooF <- read.tree("F80_10_NEW")

#Robinson Fould distance (Depends on topology of trees)
RF_20_1F <- RF.dist(aF,bF,normalize = TRUE)
#path distance (Path difference)
P_20_1F  <- path.dist(aF,bF)
RF_20_2F <- RF.dist(aF,cF,normalize = TRUE)
P_20_2F <- path.dist(aF,cF)
RF_20_3F <- RF.dist(aF,dF,normalize = TRUE)
P_20_3F <- path.dist(aF,dF)
RF_20_4F <- RF.dist(aF,eF,normalize = TRUE)
P_20_4F <- path.dist(aF,eF)
RF_20_5F <- RF.dist(aF,fF,normalize = TRUE)
P_20_5F <- path.dist(aF,fF)
RF_20_6F <- RF.dist(aF,gF,normalize = TRUE)
P_20_6F <- path.dist(aF,gF)
RF_20_7F <- RF.dist(aF,hF,normalize = TRUE)
P_20_7F <- path.dist(aF,hF)
RF_20_8F <- RF.dist(aF,iF,normalize = TRUE)
P_20_8F <- path.dist(aF,iF)
RF_20_9F <- RF.dist(aF,jF,normalize = TRUE)
P_20_9F <- path.dist(aF,jF)
RF_20_10F <- RF.dist(aF,kF,normalize = TRUE)
P_20_10F <- path.dist(aF,kF)
RF_40_1F <- RF.dist(aF,lF,normalize = TRUE)
P_40_1F <- path.dist(aF,lF)
RF_40_2F <- RF.dist(aF,mF,normalize = TRUE)
P_40_2F <- path.dist(aF,mF)
RF_40_3F <- RF.dist(aF,nF,normalize = TRUE)
P_40_3F <- path.dist(aF,nF)
RF_40_4F <- RF.dist(aF,oF,normalize = TRUE)
P_40_4F <- path.dist(aF,oF)
RF_40_5F <- RF.dist(aF,pF,normalize = TRUE)
P_40_5F <- path.dist(aF,pF)
RF_40_6F <- RF.dist(aF,qF,normalize = TRUE)
P_40_6F <- path.dist(aF,qF)
RF_40_7F <- RF.dist(aF,rF,normalize = TRUE)
P_40_7F <- path.dist(aF,rF)
RF_40_8F <- RF.dist(aF,sF,normalize = TRUE)
P_40_8F <- path.dist(aF,sF)
RF_40_9F <- RF.dist(aF,tF,normalize = TRUE)
P_40_9F <- path.dist(aF,tF)
RF_40_10F <- RF.dist(aF,uF,normalize = TRUE)
P_40_10F <- path.dist(aF,uF)
RF_60_1F <- RF.dist(aF,vF,normalize = TRUE)
P_60_1F <- path.dist(aF,vF)
RF_60_2F <- RF.dist(aF,wF,normalize = TRUE)
P_60_2F <- path.dist(aF,wF)
RF_60_3F <- RF.dist(aF,xF,normalize = TRUE)
P_60_3F <- path.dist(aF,xF)
RF_60_4F <- RF.dist(aF,yF,normalize = TRUE)
P_60_4F <- path.dist(aF,yF)
RF_60_5F <- RF.dist(aF,zF,normalize = TRUE)
P_60_5F <- path.dist(aF,zF)
RF_60_6F <- RF.dist(aF,aaF,normalize = TRUE)
P_60_6F <- path.dist(aF,aaF)
RF_60_7F <- RF.dist(aF,bbF,normalize = TRUE)
P_60_7F <- path.dist(aF,bbF)
RF_60_8F <- RF.dist(aF,ccF,normalize = TRUE)
P_60_8F <- path.dist(aF,ccF)
RF_60_9F <- RF.dist(aF,ddF,normalize = TRUE)
P_60_9F <- path.dist(aF,ddF)
RF_60_10F <- RF.dist(aF,eeF,normalize = TRUE)
P_60_10F <- path.dist(aF,eeF)
RF_80_1F <- RF.dist(aF,ffF,normalize = TRUE)
P_80_1F <- path.dist(aF,ffF)
RF_80_2F <- RF.dist(aF,ggF,normalize = TRUE)
P_80_2F <- path.dist(aF,ggF)
RF_80_3F <- RF.dist(aF,hhF,normalize = TRUE)
P_80_3F <- path.dist(aF,hhF)
RF_80_4F <- RF.dist(aF,iiF,normalize = TRUE)
P_80_4F <- path.dist(aF,iiF)
RF_80_5F <- RF.dist(aF,jjF,normalize = TRUE)
P_80_5F <- path.dist(aF,jjF)
RF_80_6F <- RF.dist(aF,kkF,normalize = TRUE)
P_80_6F <- path.dist(aF,kkF)
RF_80_7F <- RF.dist(aF,llF,normalize = TRUE)
P_80_7F <- path.dist(aF,llF)
RF_80_8F <- RF.dist(aF,mmF,normalize = TRUE)
P_80_8F <- path.dist(aF,mmF)
RF_80_9F <- RF.dist(aF,nnF,normalize = TRUE)
P_80_9F <- path.dist(aF,nnF)
RF_80_10F <- RF.dist(aF,ooF,normalize = TRUE)
P_80_10F <- path.dist(aF,ooF)
#plot Robinson Fould distance
x_axis <- c("20","40","60","80")
par(mfrow=c(2,5))
GRF_1F <- c(RF_20_1F,RF_40_1F,RF_60_1F,RF_80_1F)
plot(x_axis,GRF_1F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance ",main="RFdist_01",xlim=c(0,80),ylim=rev(range(GRF_1F)))
GRF_2F <- c(RF_20_2F,RF_40_2F,RF_60_2F,RF_80_2F)
plot(x_axis,GRF_2F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance",main="RFdist_02",ylim=rev(range(GRF_2F)))
GRF_3F <- c(RF_20_3F,RF_40_3F,RF_60_3F,RF_80_3F)
plot(x_axis,GRF_3F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance",main="RFdist_03",ylim=rev(range(GRF_3F)))
GRF_4F <- c(RF_20_4F,RF_40_4F,RF_60_4F,RF_80_4F)
plot(x_axis,GRF_4F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance",main="RFdist_04",ylim=rev(range(GRF_4F)))
GRF_5F <- c(RF_20_5F,RF_40_5F,RF_60_5F,RF_80_5F)
plot(x_axis,GRF_5F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance",main="RFdist_05",ylim=rev(range(GRF_5F)))
GRF_6F <- c(RF_20_6F,RF_40_6F,RF_60_6F,RF_80_6F)
plot(x_axis,GRF_6F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance",main="RFdist_06",ylim=rev(range(GRF_6F)))
GRF_7F <- c(RF_20_7F,RF_40_7F,RF_60_7F,RF_80_7F)
plot(x_axis,GRF_7F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF disstance",main="RFdist_07",ylim=rev(range(GRF_7F)))
GRF_8F <- c(RF_20_8F,RF_40_8F,RF_60_8F,RF_80_8F)
plot(x_axis,GRF_8F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance",main="RFdist_08",ylim=rev(range(GRF_8F)))
GRF_9F <- c(RF_20_9F,RF_40_9F,RF_60_9F,RF_80_9F)
plot(x_axis,GRF_9F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance",main="RFdist_09",ylim=rev(range(GRF_9F)))
GRF_10F <- c(RF_20_10F,RF_40_10F,RF_60_10F,RF_80_10F)
plot(x_axis,GRF_10F, type = "b" , col="red", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="RF distance",main="RFdist_10",ylim=rev(range(GRF_10F)))

#par(mfrow=c(2,5))
#PLot path distance
GP_1F <- c(P_20_1F,P_40_1F,P_60_1F,P_80_1F)
plot(x_axis,GP_1F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_01",ylim=rev(range(GP_1F)))
GP_2F <- c(P_20_2F,P_40_2F,P_60_2F,P_80_2F)
plot(x_axis,GP_2F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_02",ylim=rev(range(GP_2F)))
GP_3F <- c(P_20_3F,P_40_3F,P_60_3F,P_80_3F)
plot(x_axis,GP_3F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_03",ylim=rev(range(GP_3F)))
GP_4F <- c(P_20_4F,P_40_4F,P_60_4F,P_80_4F)
plot(x_axis,GP_4F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_04",ylim=rev(range(GP_4F)))
GP_5F <- c(P_20_5F,P_40_5F,P_60_5F,P_80_5F)
plot(x_axis,GP_5F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_05",ylim=rev(range(GP_5F)))
GP_6F <- c(P_20_6F,P_40_6F,P_60_6F,P_80_6F)
plot(x_axis,GP_6F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_06",ylim=rev(range(GP_6F)))
GP_7F <- c(P_20_7F,P_40_7F,P_60_7F,P_80_7F)
plot(x_axis,GP_7F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_07",ylim=rev(range(GP_7F)))
GP_8F <- c(P_20_8F,P_40_8F,P_60_8F,P_80_8F)
plot(x_axis,GP_8F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_08",ylim=rev(range(GP_8F)))
GP_9F <- c(P_20_9F,P_40_9F,P_60_9F,P_80_9F)
plot(x_axis,GP_9F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_09",ylim=rev(range(GP_9F)))
GP_10F <- c(P_20_10F,P_40_10F,P_60_10F,P_80_10F)
plot(x_axis,GP_10F, type = "b" , col="blue", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Path distance",main="pathdist_10",ylim=rev(range(GP_10F)))

library(ape)
#Newick to distancematrix
DM_100F <- cophenetic(aF)
DM_20_1F <- cophenetic(bF)
DM_20_2F <- cophenetic(cF)
DM_20_3F <- cophenetic(dF)
DM_20_4F <- cophenetic(eF)
DM_20_5F <- cophenetic(fF)
DM_20_6F <- cophenetic(gF)
DM_20_7F <- cophenetic(hF)
DM_20_8F <- cophenetic(iF)
DM_20_9F <- cophenetic(jF)
DM_20_10F <- cophenetic(kF)
DM_40_1F <- cophenetic(lF)
DM_40_2F <- cophenetic(mF)
DM_40_3F <- cophenetic(nF)
DM_40_4F <- cophenetic(oF)
DM_40_5F <- cophenetic(pF)
DM_40_6F <- cophenetic(qF)
DM_40_7F <- cophenetic(rF)
DM_40_8F <- cophenetic(sF)
DM_40_9F <- cophenetic(tF)
DM_40_10F <- cophenetic(uF)
DM_60_1F <- cophenetic(vF)
DM_60_2F <- cophenetic(wF)
DM_60_3F <- cophenetic(xF)
DM_60_4F <- cophenetic(yF)
DM_60_5F <- cophenetic(zF)
DM_60_6F <- cophenetic(aaF)
DM_60_7F <- cophenetic(bbF)
DM_60_8F <- cophenetic(ccF)
DM_60_9F <- cophenetic(ddF)
DM_60_10F <- cophenetic(eeF)
DM_80_1F <- cophenetic(ffF)
DM_80_2F <- cophenetic(ggF)
DM_80_3F <- cophenetic(hhF)
DM_80_4F <- cophenetic(iiF)
DM_80_5F <- cophenetic(jjF)
DM_80_6F <- cophenetic(kkF)
DM_80_7F <- cophenetic(llF)
DM_80_8F <- cophenetic(mmF)
DM_80_9F <- cophenetic(nnF)
DM_80_10F <- cophenetic(ooF)
#function to generate CADM results
CADM <- function(DM){
  #add two matrics together
  AB <- rbind(DM_100F, DM)
  cadm_global <- CADM.global(AB, 2, 6796)$congruence_analysis[1,]
  return(cadm_global)
}
cadm_global <- CADM.global(AB, 2, 6796)
#cadm_AB <- CADM(DM_B)
#cadm_AB$congruence_analysis
#Use CADM function to compare backbone trees with the complete tree
CADM(DM_20_1F)
CADM(DM_20_2)
CADM(DM_20_3)
CADM(DM_20_4)
CADM(DM_20_5)
CADM(DM_20_6)
CADM(DM_20_7)
CADM(DM_20_8)
CADM(DM_20_9)
CADM(DM_20_10)
CADM(DM_40_1)
CADM(DM_40_2)
CADM(DM_40_3)
CADM(DM_40_4)
CADM(DM_40_5)
CADM(DM_40_6)
CADM(DM_40_7)
CADM(DM_40_8)
CADM(DM_40_9)
CADM(DM_40_10)
CADM(DM_60_1)
CADM(DM_60_2)
CADM(DM_60_3)
CADM(DM_60_4)
CADM(DM_60_5)
CADM(DM_60_6)
CADM(DM_60_7)
CADM(DM_60_8)
CADM(DM_60_9)
CADM(DM_60_10)
CADM(DM_80_1)
CADM(DM_80_2)
CADM(DM_80_3)
CADM(DM_80_4)
CADM(DM_80_5)
CADM(DM_80_6)
CADM(DM_80_7)
CADM(DM_80_8)
CADM(DM_80_9)
CADM(DM_80_10)

par(mfrow=c(2,5))
#plot congruence among distance matric
CADM_1 <- c(CADM(DM_20_1),CADM(DM_40_1),CADM(DM_60_1),CADM(DM_80_1))
plot(x_axis,CADM_1, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_1",ylim=(0:1))
CADM_2 <- c(CADM(DM_20_2),CADM(DM_40_2),CADM(DM_60_2),CADM(DM_80_2))
plot(x_axis,CADM_2, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_2",ylim=(0:1))
CADM_3 <- c(CADM(DM_20_3),CADM(DM_40_3),CADM(DM_60_3),CADM(DM_80_3))
plot(x_axis,CADM_3, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_3",ylim=(0:1))
CADM_4 <- c(CADM(DM_20_4),CADM(DM_40_4),CADM(DM_60_4),CADM(DM_80_4))
plot(x_axis,CADM_4, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_4",ylim=(0:1))
CADM_5 <- c(CADM(DM_20_5),CADM(DM_40_5),CADM(DM_60_5),CADM(DM_80_5))
plot(x_axis,CADM_5, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_5",ylim=(0:1))
CADM_6 <- c(CADM(DM_20_6),CADM(DM_40_6),CADM(DM_60_6),CADM(DM_80_6))
plot(x_axis,CADM_6, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_6",ylim=(0:1))
CADM_7 <- c(CADM(DM_20_7),CADM(DM_40_7),CADM(DM_60_7),CADM(DM_80_7))
plot(x_axis,CADM_7, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_7",ylim=(0:1))
CADM_8 <- c(CADM(DM_20_8),CADM(DM_40_8),CADM(DM_60_8),CADM(DM_80_8))
plot(x_axis,CADM_8, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_8",ylim=(0:1))
CADM_9 <- c(CADM(DM_20_9),CADM(DM_40_9),CADM(DM_60_9),CADM(DM_80_9))
plot(x_axis,CADM_9, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_9",ylim=(0:1))
CADM_10 <- c(CADM(DM_20_10),CADM(DM_40_10),CADM(DM_60_10),CADM(DM_80_10))
plot(x_axis,CADM_10, type = "b" , col="purple", lwd =5, pch=19, xlab= "The level of backbone tree (%)", ylab="Congruence",main="CADM_10",ylim=(0:1))

